### ISSUE TITLE
Hide the enemy life bar.

### ISSUE THREAD

**Issue by carlos026** [carlos026/ffxTrainer#2]
Hide enemy life bar if enemy dies or has no enemy in some position.

**Comment by knando** [comment]
Added first enemy data to a panel and added code to hide it when the enemy is dead.
Missing solution for the other enemies.
Change made alongside @carlos026 - thank you!

**Comment by knando** [comment]
Added remaining enemies data to panels and added code to hide them when the enemies are dead;
Run tests to clone panels to make array usage possible in the future, **but it failed**;
Fixed some bugs with blinking buttons, including _Kill All_;
Kill all now disappears when no enemies remain;
Max health is now increased if all enemies got killed (max reduced back to zero) and then any is brought back.

I believe this issue may be closed soon @carlos026

**Comment by knando** [comment]
Now the application screen goes to back after all enemies are dead so the game screen is not blocked by it outside battles.
This was done because hiding the panels after enemies are killed left the app screen empty.
